### ISSUE TITLE
Uses unmaintained/obsolete nose testing framework

### ISSUE THREAD

**Issue by jnahmias** [frederickjansen/polyline#11]
Hello,

This report comes from the Debian bug tracker, [Bug#1018439](https://bugs.debian.org/1018439)

Polyline still uses nose [1], which is an obsolete testing framework for
Python, dead and unmaintained since 2015 [2][3].

It would be good to port polyline to one of the alternatives: nose2 [4], pytest [5]
or unittest from Python standard library [6].

There is a script called nose2pytest [7] which can assist with migrating from
nose to pytest.

Any interest in a PR that addresses this? Any particular direction / alternative you'd prefer?

[1]: https://tracker.debian.org/pkg/nose
[2]: https://github.com/nose-devs/nose/commit/0f40fa995384afad
[3]: https://pypi.org/project/nose/#history
[4]: https://docs.nose2.io/en/latest/
[5]: https://docs.pytest.org/en/latest/
[6]: https://docs.python.org/3/library/unittest.html
[7]: https://github.com/pytest-dev/nose2pytest

**Comment by frederickjansen** [comment]
Hi @jnahmias, thanks for bringing this up. I had plans on porting the tests to PyTest (along with some other structural changes). If you want to submit a pull request please feel free, otherwise I'll take care of it.

**Comment by frederickjansen** [comment]
Fixed in #12
