### ISSUE TITLE
URL safe encoding

### ISSUE THREAD

**Issue by pedro-cf** [frederickjansen/polyline#17]
Is it possible to generate URL safe encoded strings? (only uses a-z, A-Z, 0-9, and URL safe characters like + * _ -.)

Similar to: https://github.com/LiveBy/url-safe-polyline

**Comment by frederickjansen** [comment]
Hi @pedro-cf, this is currently not supported. I would probably add this function to a separate project, or advise people to use something like https://github.com/heremaps/flexible-polyline.
